# Generated by Django 4.1.1 on 2022-09-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, choices=[('NP', 'Not-Paid'), ('P', 'Paid')], max_length=2, null=True, verbose_name='وضعیت سفارش'),
        ),
    ]
