# Generated by Django 4.1.1 on 2022-10-12 07:16

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
