# Generated by Django 4.1.1 on 2022-09-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='slug',
        ),
    ]
