# Generated by Django 4.1.1 on 2022-09-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_author',
            field=models.BooleanField(default=1, verbose_name='is author?'),
            preserve_default=False,
        ),
    ]
