# Generated by Django 4.1.1 on 2022-09-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
                ('active', models.BooleanField(default=True, verbose_name='active?')),
                ('datetime_created', models.DateTimeField(verbose_name='datetime_created')),
                ('datetime_modified', models.DateTimeField(verbose_name='datetime_modified')),
            ],
        ),
    ]
